defaults:
  - scope:
      path: ""
    values:
      layout: "default"

#source: ./src

#destination: ./public

sass:
  sass_dir: assets/_sass
  style: compressed

exclude: [
  src,
  node_modules,
  package.json,
  package-lock.json,
  rollup.config.js,
  webpack.config.js,
  Gemfile,
  Gemfile.lock,
  assets/_sass,
  assets/_js,
  example
]

title: '@pix8/Lib Pagination'
#logo: /assets/img/logo.png
logo: /assets/img/pixie-dust.gif
description: A JavaScript Pagination module that returns an array of indices relative to the current page, total number of pages and range of pages you wish to serve. Useful for Adonis.js.
show_downloads: true
google_analytics:

repository: pix8/lib-pagination
#theme: jekyll-theme-minimal
